diem/client-sdk-python

README.md, src/libra/chain_ids.py, src/libra/identifier.py, src/libra/libra_types/__init__.py, src/libra/testnet.py, tests/test_identifier.py
HRPS mapping is useful for get back hrp by a configured chain id which is int value.
=> add chain ids and identifiers' hrp mapping

src/libra/txnmetadata.py, tests/test_testnet.py
test_get_account_state_with_proof_with_version is removed because: 
Server side drops old account state data, hence request will fail when we request a very old version.
Hence this test is not valid, and we need fix server side by removing the version params too.
=> remove an invalid test and fix a method annotation bug

.github/workflows/build.yml, src/diem/offchain/payment_command.py, src/diem/offchain/types/__init__.py, tests/test_offchain_command.py
When create a new command from existing payment command, pass in list of metadata will be appended into existing metadata list.
=> new command with metadata appended

examples/vasp/test_offchain_error_cases.py, src/diem/offchain/types/command_types.py, tests/test_offchain_types.py
Other enum values like status are using underscore for multi-words values. This PR changes error code to use underscore too.
=> change error code to use underscore instead of hyphen

src/diem/jsonrpc/client.py, tests/test_testnet.py
Temp solution to ignore transaction re-submit error when retrying
submit transaction for stale response errors.
When server side fix https://github.com/diem/diem/pull/7174 is deployed,
we will change to not capture any exception in  jsonrpc.Client#submit.
Won't release a new version until this is fixed.
=> temp fix build by capturing re-submit transaction error

requirements.txt, src/diem/jsonrpc/client.py
Server side mempool has been changed to ignore duplicated txns, it will not raise "Failed to update gas price" error anymore
=> remove the temp solution code that is not needed anymore.

setup.py, src/diem/offchain/jws.py, tests/test_offchain_jws.py
For unknown reason, python 3.7 may not render the text substituted.
=> change to not use f-string for formatting string with text

examples/tests/test_offchain_error_cases.py, src/diem/offchain/client.py, src/diem/offchain/types/command_types.py
1. unknown_actor_address to unknown_address
2. invalid_x_request_sender_address to invalid_http_header
=> rename error codes according to dip-1

examples/tests/test_offchain_error_cases.py, src/diem/offchain/client.py, tests/test_offchain_client.py
As it involves float point converting, relax this validation to avoid rounding difference comparing with the Diem Move VM validation logic.
=> Use ceil of the calculated exchanged xdx amount for checking under the limit

examples/refund.py, examples/stubs.py, examples/tests/test_offchain_error_cases.py, examples/vasp/wallet.py, src/diem/local_account.py, src/diem/offchain/client.py, src/diem/testnet.py, tests/conftest.py, tests/test_local_account.py, tests/test_offchain_client.py, tests/test_testnet.py
1. export to dict and import from dict: this way, we can write the LocalAccount as config into config file.
2. moved some testnet utils functions into LocalAccount as generic utils:
1. create transaction from a script
2. submit and wait for transaction executed
3. config transaction fields: gas currency code, max gas amount, gas
unit price and expire duration.
3. merged testnet gen_vasp_account and gen_account
4. add hrp to LocalAccount to simplify encoding account identifier for the account address
=> improve LocalAccount and testnet utils

src/diem/testing/miniwallet/client.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/test_create_test_account.py, src/diem/testing/suites/test_miniwallet_api.py, tests/miniwallet/conftest.py, tests/miniwallet/test_api.py
1. standalone test file for all tests related to creating test account.
2. for clear names for each test cases.
3. split clients setup into multiple fixture functions, so that we don't need start stub client if only run tests that are not required a stub wallet.
4. moved create account with invalid data tests into python sdk miniwallet test suites.
=> re-organize tests for creating test account

src/diem/__VERSION__.py, src/diem/testing/cli/click.py
this change ensures we can do:
```
dmw test -v
```
instead of `dmw test -v true`
and same for option `--enable-debug-api`
add pytest "-s" and "-v" for dmw test verbose option
=> fix dmw cli flag options and dmw test verbose option

src/diem/local_account.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/diem_account.py, src/diem/testing/miniwallet/app/event_puller.py, src/diem/testing/miniwallet/app/models.py, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/test_miniwallet_api.py, src/diem/testing/suites/test_receive_payment.py, tests/test_local_account.py
1. Refund when subaddress is unknown
2. Creates a refund txn if received a diem txn that has refund metadata
3. Log instead of os._exit when background tasks raised error. (os._exit kills all log and exception details when running test, hence it is not a good idea to just exit.)
4. Created a pending_income_account for parking all invalid payment received funds.
5. Log account and pending_income_account events for context when test failed.
6. Always create a Subaddress entity to link subaddress and account id when creating a new subaddress for transaction, this way we can always find back account id by an onchain metadata subaddress
=> MiniWallet should refund when received payment with unknown subaddress

mini-wallet.md, src/diem/__VERSION__.py, src/diem/testing/cli/click.py, src/diem/testing/miniwallet/__init__.py, src/diem/testing/miniwallet/config.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/envs.py
add host/port options to MW test startup, so that counterparties can find it at the correct place on chain
=> Add host/port option for identifying source MW during test

src/diem/__VERSION__.py, src/diem/testing/miniwallet/__init__.py, src/diem/testing/miniwallet/app/__init__.py, src/diem/testing/miniwallet/app/event_puller.py, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/test_receive_payment.py, src/diem/txnmetadata.py, tests/test_txnmetadata.py
Add test cases:
1. receive payment with invalid metadata: blank or unknown bytes metadata
2. receive payment with general metadata
3. receive payment with general metadata and invalid subaddress: including None, empty, too big and unknown subaddresses
=> test receive payment with general metadata and invalid to subaddress

src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/event_puller.py, src/diem/testing/miniwallet/app/falcon.py, src/diem/testing/miniwallet/app/models.py, src/diem/testing/miniwallet/client.py, src/diem/testing/miniwallet/config.py, src/diem/testing/suites/test_miniwallet_api.py, src/diem/testing/suites/test_receive_payment.py, src/diem/txnmetadata.py, tests/test_txnmetadata.py
1. added log for processing receive payment events
2. changed to log when submitted transaction failed instead of creating event.
3. changed miniwallet client request & response log level to debug, most of them are duplicated with server side log.
4. added tests:  test_receive_payment_with_general_metadata_and_invalid_from_subaddress and test_receive_payment_with_general_metadata_and_invalid_subaddresses
5. changed txnmetadata.general_metadata to return general metadata bytes instead of blank bytes, which is confusing.
=> add receive payment with general metadata and invalid from subaddress

src/diem/testing/miniwallet/app/event_puller.py, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/test_receive_payment.py
1. log error with http response code and body when miniwallet client received response code > 300, this highlights the error response content.
2. changed some `logger.error` to `logger.exception`, because `logger.exception` includes error and stacktrace by default.
3. extract out `_find_refund_account_id` function, because `_save_payment_txn` method is too complex (lint complained)
4. extracted out a `find_event` func from `wait_for_event` function in miniwallet RestClient class, was used in test, but later removed from test, I think it's good refactoring, so kept `find_event` method.
5. technically RefundMetadata should only be used for refunding GeneralMetadata invalid subaddress case, for all other cases (like invalid travel rule metadata), we all refund to pending income account, …
=> add receive payment with travel rule metadata test cases

src/diem/local_account.py, src/diem/testing/cli/click.py, src/diem/testing/miniwallet/config.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/envs.py, src/diem/utils.py, tests/test_testing_cli.py
1. added a logfile option to dmw test command
2. added option to `dmw test` and `dmw start-server` commands for importing diem account configuration
3. added a new command `dmw gen-diem-account-config` for generating simple diem account config file as template for creating the config for `dmw test` or `dmw start-server`
=> add options to dmw commands for supporting host MiniWallet.

examples/tests/test_offchain_error_cases.py, examples/vasp/wallet.py, src/diem/__VERSION__.py, src/diem/offchain/client.py, src/diem/testing/miniwallet/app/app.py, tests/test_offchain_client.py
1. split deserializing request object and payment command validation logic into 2 separated util functions
2. update example wallet and mini-wallet to call separated util functions, and handle the response cid properly.
3. added deprecated warning to offchain client process_inbound_request function, should be removed later.
=> fix offchain module missing response cid when payment command validation failed.

src/diem/offchain/payment_state.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/models.py, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/test_payment.py
* added special Account property for setting up mini-wallet stub app to always abort the PaymentCommand when KYC is soft_matched. We don't add this property to mini-wallet API specification, because a wallet application does not need it for any test cases.
* integration test is added to validate the change
=> off-chain payment command abort when soft_match

README.md, examples/create_child_vasp.py, examples/tests/test_offchain_error_cases.py, examples/vasp/wallet.py, src/diem/__init__.py, src/diem/testing/__init__.py, src/diem/testing/cli/click.py, src/diem/testing/local_account.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/diem_account.py, src/diem/testing/miniwallet/config.py, src/diem/testnet.py, tests/conftest.py, tests/test_local_account.py, tests/test_offchain_jws.py, tests/test_offchain_types.py, tests/test_testing_cli.py, tests/test_testnet.py
* `LocalAccount` should only be used in test environment, move it into testing package and update codebase to import it from diem.testing package.
* For backwards compatible, we still import LocalAccount in diem package, may remove when we bump up major version of SDK.
=> move local_account module into testing package

src/diem/__VERSION__.py, src/diem/testing/local_account.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/models.py, src/diem/testing/miniwallet/app/static/openapi.yaml, src/diem/testing/suites/test_create_test_account.py, src/diem/testing/suites/test_generate_account_payment_uri.py, tests/miniwallet/test_store.py
Feedback from Rashmi when implementing Novi mini-wallet proxy, the following fields mostly like won't have meaningful use cases, and we saw similar implementation pattern in DRW proxy as well. 
1. removed kyc_data in create account response: most likely server side just return the data in the request.
2. removed currency and amount in generated payment uri response: most likely server side just return the data in the request.
=> mini-wallet api change: remove response fields that don't have clear use cases.

src/diem/offchain/__init__.py, src/diem/offchain/types/__init__.py, src/diem/testing/miniwallet/app/api.py, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/test_offchain_protocol_error_cases.py, src/diem/testing/suites/test_receive_payment.py, src/diem/testing/suites/test_send_payment.py
1. missing / invalid x-request-id
2. missing / invalid x-request-sender-address
3. added mini-wallet AccountResource#generate_account_identifier for sharing generating account identifier logic across tests
4. added some documents to mini-wallet AccountResource methods.
=> add offchain api protocol error cases for missing/invalid http headers

examples/tests/test_offchain_error_cases.py, src/diem/offchain/__init__.py, src/diem/offchain/client.py, src/diem/offchain/types/__init__.py, src/diem/offchain/types/command_types.py, src/diem/testing/local_account.py, src/diem/testing/suites/test_offchain_protocol_error_cases.py, tests/test_offchain_types.py
1. Change deserializing CommandRequestObject JSON into 2 steps: first deserialize CommandRequestObject without command field, and raise all deserialization error as protocol_error, then deserialize Command object based on command_type and raise any deserialization error as command_error.
2. add test_x_request_sender_is_valid_but_no_compliance_key
3. add test_invalid_jws_message_body_that_misses_parts
4. test_invalid_jws_message_signature
=> add off-chain protocol error test cases: invalid x_request_sender_address, jws, and jws signature

requirements.txt, src/diem/testing/cli.py, src/diem/testing/miniwallet/app/api.py, src/diem/testing/miniwallet/config.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/envs.py, tests/miniwallet/conftest.py
1. remove `test_debug_api` environment variable and option.
2. renamed `enable_debug_api` to `disable_events_api`, and changed default value from True to False.
3. lock falcon version to 2.0.0 in test env.
=> make account events api enabled by default

src/diem/testing/suites/test_generate_account_payment_uri.py, tests/miniwallet/test_api.py
A VASP may not need to use subaddress to receive a payment if the child VASP account is one for a specific user / organization account, or parent VASP created one child VASP account per user.
Thus we remove subaddress assertion in the test generating payment URI.
Technically, as long as wallet application can correctly receive a payment by the generated payment URI, then it should be fine.
=> relax test assersion: do not assume generated account identifier has subaddress

Makefile, src/diem/testing/miniwallet/app/api.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/models.py, src/diem/testing/miniwallet/app/static/openapi.yaml, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/test_create_test_account.py, src/diem/testing/suites/test_offchain_protocol_error_cases.py, tests/miniwallet/test_api.py, tests/miniwallet/test_models.py
From user's feedback, use defined KycDataObject struct instead of JSON-encoded string for the kyc data fields in the request / response, simplify the serialization and deserialization of the request / response objects.
=> Change to use offchain KycDataObject struct for KYC data fields in mini-wallet API request/response

src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/event_puller.py, src/diem/testing/miniwallet/app/models.py, tests/miniwallet/test_models.py
This is helpful when debugging test failure, the output log or assertion failure may include events related to mini-wallet transactions, adding a type to tell what is type of the transaction can clarify why the transaction is created.
=> add Transaction#type to mini-wallet transaction type

src/diem/offchain/types/__init__.py, src/diem/testing/miniwallet/app/api.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/suites/test_offchain_protocol_error_cases.py
Added tests for the following cases:
1. decoded JWS message body is invalid json
2. decoded command request object misses required field
3. decoded command request object field value is invalid ("_ObjectType", "cid")
4. decoded command request object command_type is unknown
5. decoded command request object field value type is invalid
Changed some assertions to warning, relax the requirement of return error with exactly same error type, field and code, because some errors can use different code (for example invalid command_type, can use invalid_field_value or unknown_command_type)
=> add offchain protocol error cases: invalid json or command request object

src/diem/__VERSION__.py, src/diem/testing/miniwallet/app/api.py, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/__init__.py, tests/miniwallet/test_client.py
1. The mini-wallet client used by test suite will send requests with http header `X-Test-Case`, which is set with PYTEST_CURRENT_TEST
2. SDK mini-wallet application will log request info with the `x-test-case` header value
=> test suite calls to mini-wallet API with running test case http header

.github/workflows/build.yml, Makefile, src/diem/testing/local_account.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/diem_account.py, src/diem/testing/miniwallet/config.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/test_offchain_protocol_error_cases.py, src/diem/testing/suites/test_payment_command.py, src/diem/testnet.py, tests/miniwallet/test_diem_account.py, tests/test_local_account.py
1. Hide diem account usages in DiemAccount class.
2. Init 2 ChildVASP accounts for mini-wallet application
3. Random pick a child vasp account for sending / receiving payment
=> mini-wallet app: init child vasp accounts for sending and receiving payments

src/diem/__VERSION__.py, src/diem/jsonrpc/client.py, src/diem/testing/local_account.py, tests/test_testnet.py
See submit inline document for details.
=> Fix jsonrpc client bug: submit should not retry on StaleResponseError

src/diem/offchain/__init__.py, src/diem/offchain/reference_id_command.py, src/diem/offchain/types/__init__.py, src/diem/offchain/types/command_types.py, tests/test_offchain_types.py
Adding data types for reference ID exchange as defined by DIP10
=> Add reference ID exchange object types

Makefile, src/diem/testing/cli.py, src/diem/testing/suites/test_offchain_protocol_error_cases.py, tests/test_testing_cli.py
When created a new account in the test, we should reset it's hrp with stub wallet application hrp.
Also fixes `dmw` cli `pytest-args` arguments parsing bug, allows use `-k "test_a or test_b"`
=> fix test_invalid_jws_message_signature uses testnet hrp bug

src/diem/testing/miniwallet/app/api.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/test_payment_command.py, src/diem/testing/suites/test_receive_payment.py
Fix mini-wallet app for handling replay commands:
1. Added offchain response cache to wallet app for ensuring same response for the same request cid.
Changes to ensure test_replay_payment_command is more stable and testing with correct KYC sample data:
1. When disabling stub wallet app background tasks, wait for background tasks completely disabled after set the disable flag.
2. Extracted out send_initial_payment_command method for tests to send initial payment command and then re-send the same command, otherwise we may not be able to get back same command if counterparty service updated the payment command.
3. Assign subaddress to transaction when it is created so that send_initial_payment_command don't need worry about subaddress.
4. Wallet app rejects KYC data if it is not match …
=> Fix mini-wallet app for handling replay commands

src/diem/__VERSION__.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/suites/test_payment_command.py
1. Validate payment command with prior payment command was accidentally removed during a refactoring, add the validation back.
2. Added tests for validating with prior payment:
1. sender.kyc_data can only be written once.
2. sender.address can only be written once.
=> fix mini-wallet app: validate payment command with prior payment command

src/diem/testing/miniwallet/client.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/test_offchain_protocol_error_cases.py, src/diem/testing/suites/test_payment_command.py, src/diem/testing/suites/test_receive_payment.py, src/diem/testing/suites/test_send_payment.py, tests/miniwallet/test_api.py
1. inline stub and target account creation into test, so that the test code is easier for readers who are not familiar with pytest fixtures
2. remove mini-wallet client new_kyc_data, use get_kyc_sample instead; get_kyc_sample matches API endpoint kyc_sample and does nothing special inside.
=> refactoring tests: inline wallet account creation and replace new_kyc_data with get_kyc_sample for readability

src/diem/testing/cli.py, tests/test_testing_cli.py
1. add `-k` option to dmw test command for running tests with matching keywords
2. add version option to dmw cli
3. add `-h` option as help option shortcut; changed `--host` and `--stub-bind-host` shortcut to `-H`
=> add couple handy options to dmw cli

Makefile, src/diem/__VERSION__.py, src/diem/diem_types/__init__.py, src/diem/jsonrpc/jsonrpc_pb2.py, src/diem/jsonrpc/jsonrpc_pb2.pyi, src/diem/stdlib/__init__.py, src/diem/testing/local_account.py
1. update diem submodule, and re-generate diem types, jsonrpc and move stdlib code for Diem 1.2 release
2. LocalAccount#create_txn accepts payload for creating transaction
3. bump up version to 1.6.0
=> Re-generate diem types, jsonrpc and move stdlib code for Diem 1.2 release

src/diem/testing/cli.py, tests/test_testing_cli.py
In docker env, we need start server with a customized base url for counterparty wallet to access the offchain api.
=> add an option for dmw to start server with customized base url

src/diem/testing/miniwallet/app/__init__.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/event_puller.py, src/diem/testing/miniwallet/app/models.py, src/diem/testing/miniwallet/app/pending_account.py, src/diem/testing/miniwallet/app/store.py, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/test_payment_command.py, tests/miniwallet/test_store.py
As we use account as data isolation in the test, it is better to just disable one account's background tasks.
=> disable account background tasks for test

src/diem/testing/cli.py, src/diem/testnet.py, tests/test_testing_cli.py
This is useful when launching target wallet application inside a docker container, which requires a wait for the server ready.
Current dmw test does some wait by retrying when first call to target wallet application, but the error output is huge and confusing, thus a specific wait can make it easier to understand what's going on for user.
=> add a wait for target wallet application ready to dmw test command

src/diem/__VERSION__.py, src/diem/testing/miniwallet/client.py, src/diem/testing/miniwallet/config.py, tests/test_testing_cli.py
Avoid reusing account configuration for running tests multiple times.
=> enforce account setup when startup the app

Makefile, docker-compose/mini-wallet-service.yaml, mini-wallet.md
Observed a user to run mini-wallet test suite in docker container with complex setup and mistakes of creating multiple mini-wallet applications. So create this example doc for users want to run test suite in docker container.
=> add example and doc for running test suite by docker container

src/diem/testing/miniwallet/app/diem_account.py, tests/miniwallet/test_diem_account.py
When sending out payment, instead of raising errors, we auto refill the account by faucet, so that the usage of mini-wallet application has better user experience as a testing wallet application.
=> miniwallet app: ensure account balance is always enough for payment

src/diem/testing/miniwallet/app/api.py, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/conftest.py
1. change log level to debug when called events api failed on the target wallet application, because the api is optional, when it is not implemented, logging an error causes confusion, thus logging a debug message is better.
2. when logging x-test-case header, only log test name, which should be good enough.
=> reduce log noise for running test suites

Makefile, src/diem/testing/miniwallet/client.py, src/diem/testing/suites/conftest.py, src/diem/testing/suites/test_payment_command.py, src/diem/testing/suites/test_receive_payment.py, src/diem/testing/suites/test_send_payment.py, tests/miniwallet/test_api.py
Removed "--log-level info " in test target, make the test failure output more close to `dmw test` default output; and we should make the assertion error more readable for easier to understand what's going wrong.
When the assertion code is in testing directory, the pytest error message will output something like this:
```
def match_balance() -> None:
>       assert account.balance(currency) == amount
E       AssertionError: assert 10000 == 10001
E        +  where 10000 = <bound method AccountResource.balance of AccountResource(client=RestClient(name='stub-wallet-client', server_url='http...equests.sessions.Session object at 0x110c99760>, logger=<Logger stub-wallet-client (WARNING)>), id='2', kyc_data=None)>('XUS')
E        +    where <bound method AccountResource.balance of …
```
=> improve assertion failure output by test suites

src/diem/testing/miniwallet/app/api.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/event_puller.py, src/diem/testing/miniwallet/app/offchain_api_v2.py, src/diem/testing/suites/offchainv2/test_payment_command.py
1. moved offchain v2 related code into offchain_api_v2.py
2. made offchain API call as an option to setup miniwallet app, so that we can plugin v3 later.
3. changed event puller to process received payment event with a events iterator, preparing for adding another type event processor.
4. merged Base, BackgroundTasks and App classes inside app.py.
=> refactoring: separate offchain v2 related code from mini-wallet app

conftest.py, requirements.txt, setup.py, src/diem/__init__.py, src/diem/auth_key.py, src/diem/constants.py, src/diem/jsonrpc/__init__.py, src/diem/jsonrpc/async_client.py, src/diem/jsonrpc/constants.py, src/diem/jsonrpc/errors.py, src/diem/jsonrpc/state.py, src/diem/testing/__init__.py, src/diem/testing/constants.py, src/diem/testing/faucet.py, src/diem/testing/local_account.py, src/diem/testnet.py, src/diem/utils.py, tests/jsonrpc/test_async_client.py, tests/test_testnet.py
Start to migrate to async client.
Created new async Faucet client inside testing package, and moved some testnet consts into testing package as well.
For moving away from configuring testnet and faucet clients by updating testnet module JSON_RPC_URL and testnet.FAUCET_URL variables, start to accepts environment variables "DIEM_JSON_RPC_URL" and "DIEM_FAUCET_URL" to setup testnet and faucet server urls for new clients.
Extract out couple new small modules in jsonrpc for sharing constants, error classes and State class between blocking client and async client.
See #313 for more details.
=> diem async jsonrpc client and faucet client

src/diem/__VERSION__.py, src/diem/jws.py, src/diem/offchain/jws.py, src/diem/testing/suites/conftest.py, tests/test_jws.py, tests/test_offchain_jws.py
1. Extract out JWS module without offchain types to diem package. We will need jws encoding and decoding message for mini-wallet API authentication later.
2. Add content detached JWS support.
see #311 for the full plan.
=> support content detached JWS

src/diem/txnmetadata.py, tests/test_txnmetadata.py
along with asyncio support, we will make a breaking change, thus remove deprecated functions
=> remove deprecated func txnmetadata.refund_metadata_from_event

src/diem/testing/miniwallet/app/app.py, src/diem/testing/miniwallet/app/diem_account.py, src/diem/testing/miniwallet/app/event_puller.py, src/diem/testing/miniwallet/app/json_input.py, src/diem/testing/miniwallet/app/models.py, src/diem/testing/miniwallet/app/offchain_api_v2.py, src/diem/testing/miniwallet/app/store.py, tests/miniwallet/test_diem_account.py
1. Move exchanging diem id with receiver address logic into create_account_payment method, so that invalid diem_id will fail early when the api is called instead of raising error and cancel transaction in background.
2. Unify the way we send payment to internal account by looking up payee account id when creating the payment transaction
3. Unify the way we send payment transaction to external account by looking up payee account identifier (init after diem id exchange)
4. Remove thread lock in store class, asyncio code runs in one thread.
=> Refactoring mini-wallet send payment transaction logic

README.md, src/diem/jsonrpc/__init__.py, src/diem/jsonrpc/async_client.py, src/diem/jsonrpc/client.py, src/diem/offchain/client.py, src/diem/testing/faucet.py, src/diem/testing/miniwallet/app/app.py, src/diem/testing/suites/basic/test_diem_id.py, src/diem/testing/suites/conftest.py, src/diem/utils.py, tests/jsonrpc/test_async_client.py, tests/miniwallet/conftest.py, tests/miniwallet/test_diem_account.py, tests/test_testnet.py
Because global testnet is slower and need more retry for resolving stale response:
1. we need longer/more retry for test code waiting for sending payment transaction, changed test to use backoff retry strategy that we used in jsonrpc client
2.  aiohttp client session seems leaking connection as close session won't close connection completely, which causes server starts reject client connection after some tests completed.
3. run all mini-wallet background tasks and send payment txns concurrently, this speeds up waiting payment txn
4. increase waiting for port ready time for testing cli because initializing mini-wallet app requires more time
Global testnet does not support diem id yet, so skip diem id specific code / test if network does not support it
=> Fix running tests with global testnet
